models:
  - name: dim_hosts_cleansed
    description: Cleansed table for airbnb hosts.
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: The id of the host. This is the primary key
        data_type: integer
        constraints:
          - type: not_null
        data_tests:
          - unique

      - name: host_name
        description: The name of the host
        data_type: string
        constraints:
          - type: not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        data_type: boolean
        data_tests:
          - accepted_values:
              arguments:
                values: [true, false]

      - name: updated_at
        data_type: timestamp

      - name: created_at
        data_type: timestamp 