version: 2

models:
  - name: dim_listings
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 1000
  
    description: Cleansed table which contains Airbnb listings.

    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null
      
      - name: host_id
        description: The host's id. References the host table
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts')
                field: host_id

      - name: room_type
        description: Type of the room/apartment
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values
  
  - name: dim_hosts
    columns:
      - name: host_id
        data_tests:
          - not_null
          - unique
      
      - name: host_name
        data_tests:
          - not_null
        
      - name: is_superhost
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']
    
  - name: dim_hosts
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
        
      - name: host_name
        data_type: string
        
      - name: is_superhost
        data_type: string

      - name: updated_at
        data_type: timestamp

      - name: created_at
        data_type: timestamp